### ISSUE TITLE
Windows are cut off weirdly in overview

### ISSUE THREAD

**Issue by dolwup** [flexagoon/rounded-window-corners#34] opened 2024-07-12 15:58 UTC
GNOME Shell Version 46.3.1

# Summary
Every window that gets its corners rounded by the extension gets cut off in weird ways in overview depending of how big it is and how far it gets scaled down

# Steps to reproduce
1. Open a window (one that gets the rounded corners effect applied)
2. Scale it reasonably big
3. Open another window and scale it up
4. Open overview

# Screenshots
![Screenshot from 2024-07-12 17-57-26](https://github.com/user-attachments/assets/fba5ffcc-85e4-47cf-ba5f-eebb41f30ddb)

**Comment by nattadasu** [comment] 2024-07-12 19:45
The issue also has been reported previously on #29 btw.

**Comment by flexagoon** [comment] 2024-07-13 14:40
Duplicate of #29

**Closed by flexagoon** 2024-07-13 14:40 UTC
