### ISSUE TITLE
Whitelist: opposite of blacklist

### ISSUE THREAD

**Issue by Jenyyk** [flexagoon/rounded-window-corners#70] opened 2024-11-29 23:00 UTC
Say i only want rounded corners and a nice border on a single certain window type.
Basically add on top of the existing blacklist, by being able to toggle between a blacklist and a whitelist.
You can currently have custom details for a certain window type, but not all options are available to customize. (For example border and border color)
I dont think this functionality is supported right now and it would be great.

**Comment by flexagoon** [comment] 2024-11-29 23:57
Duplicate of #26

**Closed by flexagoon** 2024-11-29 23:57 UTC
