### ISSUE TITLE
The extension does not work.

### ISSUE THREAD

**Issue by cristian-home** [flexagoon/rounded-window-corners#50] opened 2024-09-26 18:48 UTC
The last update broke the extension.

![imagen](https://github.com/user-attachments/assets/1cbbd631-b53d-4d7a-9796-dfb299c07be3)

![imagen](https://github.com/user-attachments/assets/c218ee47-1de7-40e9-b1b0-4659796412b9)

```
TypeError: this._cfg.keepRoundedCorners is undefined

Stack trace:
  @file:///home/cristian/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences/pages/general.js:57:9
  pages@file:///home/cristian/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences/index.js:5:5
  fillPreferencesWindow@file:///home/cristian/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/prefs.js:23:28
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:41:18
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:26:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:17:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
  async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:126:14
  _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  ```

**Comment by flexagoon** [comment] 2024-09-26 19:16
How did you install the extension? Did you update it from Gnome Extensions?

**Comment by flexagoon** [comment] 2024-09-26 19:18
@cristian-home Please run the following command and provide the entire output here as a code block:

```bash
dconf dump /org/gnome/shell/extensions/rounded-window-corners-reborn/
```

**Comment by cristian-home** [comment] 2024-09-26 19:22
Using the Extension Manager app by Matthew Jakeman, by logging out and logging in to update the extension.

[https://flathub.org/apps/com.mattjakeman.ExtensionManager](https://flathub.org/apps/com.mattjakeman.ExtensionManager)

**Comment by flexagoon** [comment] 2024-09-26 19:25
@cristian-home please show the output of the command I wrote above

**Comment by cristian-home** [comment] 2024-09-26 19:26
![imagen](https://github.com/user-attachments/assets/eefc2450-db7b-482f-b31b-84a5d2f16be5)

```
custom-rounded-corner-settings=@a{sv} {}
global-rounded-corner-settings={'padding': <{'left': <uint32 1>, 'right': <uint32 1>, 'top': <uint32 1>, 'bottom': <uint32 1>}>, 'keep_rounded_corners': <{'maximized': <false>, 'fullscreen': <false>}>, 'border_radius': <uint32 12>, 'smoothing': <uint32 0>}
settings-version=uint32 5
```

**Comment by flexagoon** [comment] 2024-09-26 19:29
@cristian-home

uhh

I'm really not sure how this happened tbh, it was supposed to be fixed by 5d0eb93c0f9f91511a142f0aa7d0f0f3b61b4e9a and I can't reproduce this. Did you previously install the extension manually from source code or through a zip file?

For now, you can fix the issue by running:

```bash
dconf reset -f /org/gnome/shell/extensions/rounded-window-corners-reborn/
```

**Comment by cristian-home** [comment] 2024-09-26 19:45
The command `dconf reset -f /org/gnome/shell/extensions/rounded-window-corners-reborn/` fixed the problem, thanks.

**Comment by flexagoon** [comment] 2024-09-26 19:52
> Did you previously install the extension manually from source code or through a zip file?

@cristian-home ?

**Comment by cristian-home** [comment] 2024-09-26 19:56
No, I had installed it yesterday from the [https://extensions.gnome.org/](https://extensions.gnome.org/) site via the Firefox extension, and it was updated today from the Extension Manager by Matthew Jakeman app.

**Comment by 0ussamaBernou** [comment] 2024-09-26 21:52
> The last update broke the extension.
> 
> ![imagen](https://private-user-images.githubusercontent.com/4079493/371277329-1cbbd631-b53d-4d7a-9796-dfb299c07be3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczODc3ODAsIm5iZiI6MTcyNzM4NzQ4MCwicGF0aCI6Ii80MDc5NDkzLzM3MTI3NzMyOS0xY2JiZDYzMS1iNTNkLTRkN2EtOTc5Ni1kZmIyOTljMDdiZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMjE1MTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2E2Zjk0OTA1MWI2MWExMzQ1Nzc2NWU5MmJiODVlNDMxMGFlMmE4YWVlYTZlNDgyYjhiNWNmMmJmZTU4ZjA0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ypv6rylCDn6Tr-XMS6xzrG6EOTXX0MTeeL4Lw5becNE)
> 
> ![imagen](https://private-user-images.githubusercontent.com/4079493/371277430-c218ee47-1de7-40e9-b1b0-4659796412b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczODc3ODAsIm5iZiI6MTcyNzM4NzQ4MCwicGF0aCI6Ii80MDc5NDkzLzM3MTI3NzQzMC1jMjE4ZWU0Ny0xZGU3LTQwZTktYjFiMC00NjU5Nzk2NDEyYjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjZUMjE1MTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmVmODk1YjQ5ZWIxODc4YTczMDliOTA1YjAzZGVkYWU1M2E2MGZkODM0OWI5ZTgzYjc5Y2M1MTAwNmEyZjE0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.cIZC30UIdOR87yMKzrrvA3RpuKin91aF7oR2QtGsWts)
> 
> ```
> TypeError: this._cfg.keepRoundedCorners is undefined
> 
> Stack trace:
>   @file:///home/cristian/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences/pages/general.js:57:9
>   pages@file:///home/cristian/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences/index.js:5:5
>   fillPreferencesWindow@file:///home/cristian/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/prefs.js:23:28
>   _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:41:18
>   async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:26:14
>   ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:17:4
>   OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
>   async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:126:14
>   _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
>   _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
>   _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
> ```

same here, happened after  the update from extension manager

**Comment by flexagoon** [comment] 2024-09-26 22:06
Can everyone who experiences this issue please attach the output of `dconf dump /org/gnome/shell/extensions/rounded-window-corners-reborn/` to their comment?

**Comment by 0ussamaBernou** [comment] 2024-09-26 22:38
output of  `dconf dump /org/gnome/shell/extensions/rounded-window-corners-reborn/`:
```
[/]
border-color=(0.42964518070220947, 0.35815554857254028, 0.47333332896232605, 1.0)
border-width=1
global-rounded-corner-settings={'padding': <{'left': uint32 1, 'right': 1, 'top': 1, 'bottom': 1}>, 'keepRoundedCorners': <{'maximized': true, 'fullscreen': false}>, 'borderRadius': <uint32 12>, 'smoothing': <0.0>, 'enabled': <true>}
settings-version=uint32 5
skip-libadwaita-app=true
```
P.S: i did it after running this command `dconf reset -f /org/gnome/shell/extensions/rounded-window-corners-reborn/`

**Comment by memory-colors** [comment] 2024-09-27 02:36
Same here :/

Dconf dump, as requested:


dconf dump /org/gnome/shell/extensions/rounded-window-corners-reborn/
[/]
border-color=(0.094117648899555206, 0.098039217293262482, 0.11372549086809158, 1.0)
border-width=3
custom-rounded-corner-settings=@a{sv} {}
focused-shadow={'vertical_offset': 48, 'horizontal_offset': 0, 'blur_offset': 48, 'spread_radius': 50, 'opacity': 38}
global-rounded-corner-settings={'padding': <{'left': <uint32 1>, 'right': <uint32 1>, 'top': <uint32 1>, 'bottom': <uint32 1>}>, 'keep_rounded_corners': <{'maximized': <false>, 'fullscreen': <false>}>, 'border_radius': <uint32 24>, 'smoothing': <0.40000000000000002>}
settings-version=uint32 5
skip-libadwaita-app=false
unfocused-shadow={'vertical_offset': 2, 'horizontal_offset': 0, 'blur_offset': 12, 'spread_radius': 4, 'opacity': 40}

**Comment by Ego-X** [comment] 2024-09-27 07:46
dconf reset -f /org/gnome/shell/extensions/rounded-window-corners-reborn/ fixed the error.

**Comment by flexagoon** [comment] 2024-09-27 08:10
Can anyone who didn't run the `dconf reset` command yet please try running this, then log out and back in and check if that fixes the issue?

```
dconf write /org/gnome/shell/extensions/rounded-window-corners-reborn/settings-version 4
```

**Closed** 2024-09-27 08:20 UTC

**Comment by flexagoon** [comment] 2024-09-27 08:22
A fixed version is pending review:

https://extensions.gnome.org/review/58730
