### ISSUE TITLE
Conflict with Compiz Windows Effect extension

### ISSUE THREAD

**Issue by FOUR-BITS-28** [flexagoon/rounded-window-corners#63] opened 2024-10-30 11:12 UTC
Enabling both the Compiz Windows Effect and this extension causes the Compiz window wiggle effect to be clipped by this extension.

DE: Gnome 47.0
Display Server: Wayland (not tried to reproduce it in X11)

How to reproduce:
1. Install and enable both Compiz Windows Effect and this extension
2. Apply some borders and corner radius
3. Untick both skip LibHandy and LibAdwaita applications (Optional to make the rounded corners applied to all windows) 
4. Drag the window
5. Observe that the wiggle effect will be clipped by this extension

Having both of these extensions not conflict with each other is such a best thing to have. Thanks!

https://github.com/user-attachments/assets/be365053-3931-4c26-9cf6-2235faa9845b

**Comment by flexagoon** [comment] 2024-10-30 17:03
Duplicate of #14

**Closed by flexagoon** 2024-10-30 17:03 UTC
