### ISSUE TITLE
After updating the plug-in, the plug-in does not work

### ISSUE THREAD

**Issue by wxmup** [flexagoon/rounded-window-corners#52] opened 2024-09-27 00:18 UTC
I am gnome46 desktop. When I restarted my computer, the plugin prompted me that the plugin had been updated, so I logged out. After logging out, the plugin doesn't work.

Here is the error log: Extension rounded-window-corners
The extension rounded-window-corners@fxgn was set incorrectly:
``
TypeError: this._cfg.keepRoundedCorners is undefined

Stack tracking:
  @file:///home/wuxuming/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences/pages/general.js:57:9
  pages@file:///home/wuxuming/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences/index.js:5:5
  fillPreferencesWindow@file:///home/wuxuming/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences.js:23:28
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:41:18
  async* _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:26:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:17:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<<@resource://g/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource://g/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
``

![图片](https://github.com/user-attachments/assets/5b4fee00-9b96-4a9e-910e-6ca1186e462d)

**Comment by cobbdzon** [comment] 2024-09-27 00:41
Bump, I'm getting the same error

**Comment by NiffirgkcaJ** [comment] 2024-09-27 03:36
It was updated for me on GNOME 47, but it broke!

**Comment by Ego-X** [comment] 2024-09-27 07:42
I also have the same error:

The settings of extension rounded-window-corners@fxgn had an error:
```
TypeError: this._cfg.keepRoundedCorners is undefined

Stack trace:
  @file:///home/martin/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences/pages/general.js:57:9
  pages@file:///home/martin/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/preferences/index.js:5:5
  fillPreferencesWindow@file:///home/martin/.local/share/gnome-shell/extensions/rounded-window-corners@fxgn/prefs.js:23:28
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:41:18
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:26:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:17:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:139:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
```

**Comment by flexagoon** [comment] 2024-09-27 08:07
Duplicate of #50

**Closed by flexagoon** 2024-09-27 08:07 UTC
