### ISSUE TITLE
Blurry frame on some Electron apps

### ISSUE THREAD

**Issue by theme118** [flexagoon/rounded-window-corners#38] opened 2024-07-28 11:04 UTC
Hi!

It appears a blurry frame on electron apps such like Element, Vesktop or the Electron app.

With extension activated:
![imagen](https://github.com/user-attachments/assets/c22349f7-31c5-49fd-9080-6a7984d3557c)

Without extension activated:
![imagen](https://github.com/user-attachments/assets/e5c3f498-3735-43b1-bcc8-37e6ff49a472)

![imagen](https://github.com/user-attachments/assets/d2ba8c12-d720-4808-bd50-0e1744d8daa2)

# My system

- EndeavourOS
- GNOME 46
- Wayland
- Linux 6.10.1-arch1-1
- AMDGPU - AMD Radeon™ RX 580 Series

**Comment by flexagoon** [comment] 2024-07-28 16:59
Duplicate of #30

**Closed by flexagoon** 2024-07-28 16:59 UTC
