### ISSUE TITLE
Windows get pixelated on the overview

### ISSUE THREAD

**Issue by barslmn** [flexagoon/rounded-window-corners#62] opened 2024-10-26 15:40 UTC
https://github.com/user-attachments/assets/b551f14b-44cf-49a4-b6ff-d51589696f6b

As it can be seen in video, when the extension is enabled the windows get pixelated on the overview.

**Comment by barslmn** [comment] 2024-10-26 15:47
With all other extensions disabled.

https://github.com/user-attachments/assets/b9b59cd7-a3e8-43ea-9c0f-a5dd80e0a781

**Comment by flexagoon** [comment] 2024-10-27 11:58
Duplicate of #36

**Closed by flexagoon** 2024-10-27 11:58 UTC
